### ISSUE TITLE
allowFullScreen property

### ISSUE THREAD

**Issue by ynuska** [ItsAsbreuk/itsa-react-docviewer#1]
I've set the property allowFullScreen on false, but the fullscreen button it's still visible.
On click, it will open a new tab about:blank. Is it possible to just hide the button  ?

**Comment by ItsAsbreuk** [comment]
thank you for your comment, I will have a look

**Comment by ItsAsbreuk** [comment]
The `allowFullScreen` is the upperleft button that enables you to view the document full screen. This seems to work as expected. I think you are referring ti the upper right button that comes from Google Docs Viewer itself. This button has a different purpose: open the doc in a separate browsertab. 
Unfortunately Google Docs Viewer is very limited and doesn't allow you to disable it (AFAIK)
