### ISSUE TITLE
new functionality wanted: loading state

### ISSUE THREAD

**Issue by ynuska** [ItsAsbreuk/itsa-react-docviewer#2]
Sometimes it takes long until the document is displayed, I would like to detect when the document is still loading and not yet loaded.

Is it possible to extend this package with new  functionality ?  Thx!

**Comment by ItsAsbreuk** [comment]
If Google docviewer supports this than this can be done. I'll follow up

**Comment by ItsAsbreuk** [comment]
This feature is added as from the latest version 16.0.5
You will need to set the property `showLoadingMsg` **true**.
You can change the default message (loading...) with the property `loadingMsg`

**Comment by ItsAsbreuk** [comment]
And if you want to change the style, you should overrule the class `.itsa-docviewer-loading-msg`

**Comment by ynuska** [comment]
thank you for all the answers!
