### ISSUE TITLE
documentation: activatePlaces

### ISSUE THREAD

**Issue by ynuska** [ItsAsbreuk/itsa-react-docviewer#3]
Could you please add documentation  for this ? 

> componentDidMount ()
> Defined in lib/component.jsx:78
> Available since 0.0.1
> componentDidMount will call this.activatePlaces();

**Comment by ItsAsbreuk** [comment]
That's actually a bug in the documentation. Meanwhile, I've upgraded this module to extend React.Component, so that it can be used with React Fiber as well.
After looking at you other issues, I will update the code

**Comment by ItsAsbreuk** [comment]
The version is upgraded
